### ISSUE TITLE
about to wazuh-manager volumes the ossec.conf

### ISSUE THREAD

**Issue by yehaotong** [kajov/wazuh-kubernetes-helmchart#3]
when I use the wazuh-manager and try to volumes the ossec.conf,it always failed(filed in init the etc/cont-init.d/2-manager),what is the problem ? I volumes the path is:/var/ossec/etc/ossec.conf,and I see that your statefulSet.yml volume path is:/wazuh-config-mount/etc/ossec.conf,is that make me failed? ossec.conf do not need to put in /var/ossec/etc?

**Comment by kajov** [comment]
Correct by the definition the *ossec.conf* should be placed in to /var/ossec/ pathway, this is exact same pathway configuration from the wazuh official kubernetes yaml file for the manager statefulset. I will try to investigate and fix this as soon as I have time, but if you have an idea, feel free to PR and contribute to the patch :)

**Comment by kajov** [comment]
I could not replicate your issue where the volume was not existing in the pod. And have encountered no issues so far, besides the current ones where Kibana is not starting and elastic search is being weird.

As well if you look to edit the master ossec.conf I suggest you edit the config map master-config then all the changes will be translated in to the pod after you restart it.

Is that answer your qeustion @yehaotong ?

**Comment by yehaotong** [comment]
The agent's ossec.conf is configured in the configmap in the same way as yours, but I configure the content of ossec.conf to the configmap in the same way, but an error is reported, which is the same as the way I mount the error information using volumes in statefullset.yml

**Comment by yehaotong** [comment]
It's like I can't mount the manager's ossec.conf file, but I successfully mount the agent, which is a little strange@kajov

**Comment by kajov** [comment]
@yehaotong This is very strange indeed.

**Comment by kajov** [comment]
I will try to look in to this as soon as I have time, currently I'm not maintaining this project as I have other priorities tasks.

**Comment by yehaotong** [comment]
I was wondering if the path originally mounted here should not be: / var / ossec / etc / ossec.conf，it is correct to use this path in your project: / wazuh config mount / etc / ossec.conf

**Comment by kajov** [comment]
> I was wondering if the path originally mounted here should not be: / var / ossec / etc / ossec.conf，it is correct to use this path in your project: / wazuh config mount / etc / ossec.conf

It should be spaced it seemes either I managed to add the spaces or my code env did it for me. Try removing them and see if anything changes ?
