### ISSUE TITLE
Request for dashboard

### ISSUE THREAD

**Issue by Korakbhakta02** [kajov/wazuh-kubernetes-helmchart#6]
I have installed wazuh using helm chart, everything is there but how to access the dashboard, as no dashboard service is there. Please, help me regarding this issue.

**Comment by kajov** [comment]
Wazuh dashboard is accessed via Elasticsearch web ui, that you have to port-forward or expose to loadbalancer/node-port depending on your infrastructure.
Refference Elasticsearch documentation how to access the dashboard

**Comment by Korakbhakta02** [comment]
Which service actually I have to port forward as wazuh-elasticsearch and autogenerated-elasticsearch is not allowing to change the exposure?
